name: release-windows

on:
  workflow_dispatch:
  push:
    branches: [ release ]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.201

    # Install Nerdbank.GitVersioning
    - uses: dotnet/nbgv@master
      with:
        setCommonVars: true
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration=WindowsRelease

    - name: Run Windows unit tests
      run: |
        dotnet test --configuration=WindowsRelease
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifacts
        path: |
          out\windows\Installer.Windows\bin\Release\net472\*.exe
