name: release-osx

on:
  workflow_dispatch:
  push:
    branches: [ release, release-migration ]

jobs:
  build-and-lay-out:
    name: Build and lay out macOS payload
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.
        ref: release-migration

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.201
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration=MacRelease
    
    - name: Run macOS unit tests
      run: |
        dotnet test --configuration=MacRelease

    - name: Lay out payload and symbols
      run: |
        src/osx/Installer.Mac/layout.sh --configuration=MacRelease --output=payload --symbol-output=symbols

    - name: Upload payload
      uses: actions/upload-artifact@v2
      with:
        name: macos-payload
        path: payload
    
    - name: Upload symbols
      uses: actions/upload-artifact@v2
      with:
        name: macos-symbols
        path: symbols
  
  sign-payload:
    name: Sign macOS payload
    # ESRP service requires signing to run on Windows
    runs-on: windows-latest
    needs: build-and-lay-out
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: release-migration

    - name: Download payload
      uses: actions/download-artifact@v2
      with:
        name: macos-payload
        path: payload
    
    - name: Zip payload
      shell: pwsh
      run: |
        Compress-Archive -Path payload payload/payload.zip
        cd payload
        Get-ChildItem -Exclude payload.zip | Remove-Item -Recurse -Force
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Install ESRP client
      shell: pwsh
      env:
        AZ_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        az storage blob download --file esrp.zip --account-key "$env:AZ_KEY" --account-name gcmesrp --container microsoft-esrp-client --name microsoft.esrpclient.1.2.76.nupkg
        Expand-Archive -Path esrp.zip -DestinationPath .\esrp
    
    - name: Install certificates
      shell: pwsh
      env:
        AZ_VAULT: ${{ secrets.AZURE_VAULT }}
        AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
        REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
      run: |
        az keyvault secret download --vault-name "$env:AZ_VAULT" --name "$env:AUTH_CERT" --file out.pfx
        certutil -f -importpfx out.pfx
        Remove-Item out.pfx

        az keyvault secret download --vault-name "$env:AZ_VAULT" --name "$env:REQUEST_SIGNING_CERT" --file out.pfx
        certutil -f -importpfx out.pfx
        Remove-Item out.pfx
    
    - name: Run ESRP client
      shell: pwsh
      env:
        AZURE_AAD_ID: ${{ secrets.AZURE_AAD_ID }}
        # We temporarily need two AAD IDs, as we're using an SSL certificate associated
        # with an older App Registration until we have the required hardware to approve
        # the new certificate in SSL Admin.
        AZURE_AAD_ID_TEMP: ${{ secrets.AAD_ID_TEMP }}
        APPLE_KEY_CODE: ${{ secrets.APPLE_KEY_CODE }}
        APPLE_OP_CODE: ${{ secrets.APPLE_OPERATION_CODE }}
      run: |
        python .github\run_esrp_signing.py payload $env:APPLE_KEY_CODE $env:APPLE_OP_CODE --params 'Hardening' '--options=runtime' 'Entitlements' '--entitlements=entitlements.xml'
    
    - name: Unzip payload
      shell: pwsh
      run: |
        Expand-Archive signed/payload.zip -DestinationPath signed
        Remove-Item signed/payload.zip
        ls signed

    - name: Upload signed payload
      uses: actions/upload-artifact@v2
      with:
        name: macos-signed-payload
        path: |
          signed\*
  
  pack:
    name: Package macOS payload
    runs-on: macos-latest
    needs: sign-payload
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.
        ref: release-migration
    
    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.201
    
    # Install Nerdbank.GitVersioning
    - uses: dotnet/nbgv@master
      with:
        setCommonVars: true

    - name: Download signed payload
      uses: actions/download-artifact@v2
      with:
        name: macos-signed-payload
        path: payload
 
    - name: Check payload
      run: |
        ls ./payload
    
    - name: Create component package
      run: |
        src/osx/Installer.Mac/pack.sh --payload=payload/payload --version=$GitBuildVersionSimple --output=components/com.microsoft.gitcredentialmanager.component.pkg
    
    - name: Create product archive
      run: |
        src/osx/Installer.Mac/dist.sh --package-path=components --version=$GitBuildVersionSimple --output=pkg/gcm-osx-$GitBuildVersionSimple.pkg || exit 1
    
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: macos-unsigned-pkg
        path: |
          pkg/*
  
  sign-package:
    name: Sign macOS package file
    # ESRP service requires signing to run on Windows
    runs-on: windows-latest
    needs: pack
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: release-migration

    - name: Download unsigned package file
      uses: actions/download-artifact@v2
      with:
        name: macos-unsigned-pkg
        path: pkg
    
    - name: Zip unsigned package file
      shell: pwsh
      run: |
        Compress-Archive -Path pkg/*.pkg pkg/gcm-pkg.zip
        cd pkg
        Get-ChildItem -Exclude gcm-pkg.zip | Remove-Item -Recurse -Force
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Install ESRP client
      shell: pwsh
      env:
        AZ_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        az storage blob download --file esrp.zip --account-key "$env:AZ_KEY" --account-name gcmesrp --container microsoft-esrp-client --name microsoft.esrpclient.1.2.76.nupkg
        Expand-Archive -Path esrp.zip -DestinationPath .\esrp
    
    - name: Install certificates
      shell: pwsh
      env:
        AZ_VAULT: ${{ secrets.AZURE_VAULT }}
        AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
        REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
      run: |
        az keyvault secret download --vault-name "$env:AZ_VAULT" --name "$env:AUTH_CERT" --file out.pfx
        certutil -f -importpfx out.pfx
        Remove-Item out.pfx

        az keyvault secret download --vault-name "$env:AZ_VAULT" --name "$env:REQUEST_SIGNING_CERT" --file out.pfx
        certutil -f -importpfx out.pfx
        Remove-Item out.pfx
    
    - name: Run ESRP client
      shell: pwsh
      env:
        AZURE_AAD_ID: ${{ secrets.AZURE_AAD_ID }}
        # We temporarily need two AAD IDs, as we're using an SSL certificate associated
        # with an older App Registration until we have the required hardware to approve
        # the new certificate in SSL Admin.
        AZURE_AAD_ID_TEMP: ${{ secrets.AAD_ID_TEMP }}
        APPLE_KEY_CODE: ${{ secrets.APPLE_KEY_CODE }}
        APPLE_OP_CODE: ${{ secrets.APPLE_OPERATION_CODE }}
      run: |
        python .github\run_esrp_signing.py pkg $env:APPLE_KEY_CODE $env:APPLE_OP_CODE
    
    - name: Unzip signed package file
      shell: pwsh
      run: |
        Expand-Archive -LiteralPath signed\gcm-pkg.zip -DestinationPath . -Force
        Remove-Item signed\gcm-pkg.zip -Force

    - name: Upload signed package file
      uses: actions/upload-artifact@v2
      with:
        name: macos-signed-pkg
        path: .\*.pkg
  
  notarize-and-publish-signed-artifacts:
    name: Notarize and publish signed macOS artifacts
    runs-on: macos-latest
    needs: sign-package
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.
        ref: release-migration
    
    # Install Nerdbank.GitVersioning
    - uses: dotnet/nbgv@master
      with:
        setCommonVars: true

    - name: Download signed package file
      uses: actions/download-artifact@v2
      with:
        name: macos-signed-pkg
        path: pkg
    
    - name: Download signed payload
      uses: actions/download-artifact@v2
      with:
        name: macos-signed-payload
        path: payload
    
    - name: Download symbols
      uses: actions/download-artifact@v2
      with:
        name: macos-symbols
        path: symbols
    
    - name: Notarize and staple installer package
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: |
        .github/notarize-pkg.sh -id $APPLE_ID -p $APPLE_ID_PASSWORD -pkg pkg/*.pkg -pkg-info com.microsoft.gitcredentialmanager.component.pkg
    
    - name: Prepare final artifacts
      run: |
        mkdir -p ./publish/payload ./publish/payload.sym
        cp -f ./pkg/*.pkg ./publish/
        cp -Rf ./payload/* ./publish/payload/
        cp -Rf ./symbols/* ./publish/payload.sym/
        tar -czf ./publish/gcm-osx-$GitBuildVersion.tar.gz ./payload/
        tar -czf ./publish/symbols-osx.tar.gz ./symbols/
    
    - name: Publish final artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-signed-installer
        path: ./publish/*
